### PR TITLE
Latest Changes to Test

### PR DESCRIPTION
**Pull request by Karkus476**
The commit messages are enough to understand the changes.

### CODE REVIEW

**Comment by tobbi** [comment]
Great stuff! I will test it in a minute.

**Comment by Karkus476** [comment]
Wait. I need to get rid of the second last commit that was a mistake.

**Comment by tobbi** [comment]
Sure, no problem.

**Comment by Karkus476** [comment]
You can't rebase merge commits though, so how could I remove the useless second to last merge?

**Comment by tobbi** [comment]
What you could do is reset to origin/develop and then git cherry-pick.

In case something goes wrong, here are the hashes:
supertux-editor.png is now the icon for the editor  d3cf757
Stop 'Save' button opening 'Save As' Dialog …     a127648
Saving file adds it to 'Open Recent' …    767d754
Editor opens latest level on the recent levels list automatically   d513c9a
Name all SpawnPoints 'main' …     702bc27
Tilemaps are now initiated with more arguments …  afeba48
Default TileMaps have correct names and z_pos-itions    c43f40e
New Level Wizard Added  ba52f3f

**Comment by Karkus476** [comment]
That did it. I will now implement your ideas.

**Pull request merged**
